### ISSUE TITLE
运行时遇到的环境问题

### ISSUE THREAD

**Issue by winner-4** [jxylon/imgcrawler-tool#11]
作者你好，我在运行你的代码时遇到了一些环境问题，请问你有遇到过吗？该怎么解决呢？
![image](https://github.com/jxylon/imgcrawler-tool/assets/77573973/1f1b1add-d8b5-41e4-b537-a9643cd2cc73)

**Comment by ayslks** [comment]
作者你好，我这爬取Bing的图片过程中遇到如下问题，该怎么解决？
QLayout::addChildLayout: layout "verticalLayout_2" already has a parent
QLayout::addChildLayout: layout "verticalLayout" already has a parent
QLayout::addChildLayout: layout "verticalLayout_3" already has a parent
第0/1页正在下载中...
 16%|████████████▉                                                                      | 7/45 [00:07<00:42,  1.11s/it]
Traceback (most recent call last):
  File "E:\Tool\imgcrawler-tool-master\imgcrawler\crawler_ui.py", line 366, in run
    self.crawler.start_craw(2, _url=self.website)
  File "E:\Tool\imgcrawler-tool-master\imgcrawler\crawler_func.py", line 96, in start_craw
    self.download_img(url_list)
  File "E:\Tool\imgcrawler-tool-master\imgcrawler\crawler_func.py", line 56, in download_img
    suffix = img_url.split('.')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
